SELECT * FROM INSTRUCTORS
WHERE SALARY > 5500 AND FIRSTNAME ILIKE 'J%';

SELECT * FROM INSTRUCTORS
WHERE SALARY > 5500 OR FIRSTNAME ILIKE 'J%';

SELECT * FROM INSTRUCTORS
WHERE SALARY > 5000 AND FIRSTNAME ILIKE 'J%' OR
FIRSTNAME ILIKE 'P%';

SELECT * FROM STUDENTS
WHERE FIRSTNAME IS NOT NULL
ORDER BY STUDENTID ASC;

SELECT * FROM STUDENTS
WHERE AGE NOT IN (30)
ORDER BY STUDENTID ASC;