SELECT * FROM STUDENTS;
SELECT * FROM INSTRUCTORS;
SELECT * FROM COURSES;
SELECT * FROM STUDENT_COURSES;

SELECT FIRSTNAME, LASTNAME, AGE
FROM STUDENTS
ORDER BY STUDENTID ASC;

SELECT EMAIL, FIRSTNAME 
FROM INSTRUCTORS
ORDER BY HIREDATE ASC;

SELECT * FROM INSTRUCTORS
WHERE INSTRUCTORID != 3;