-- Insert students

INSERT INTO STUDENTS (FIRSTNAME, LASTNAME, AGE, EMAIL)
VALUES ('John', 'Doe', 27, 'john.doe@example.com');

-- Insert Instructor

INSERT INTO INSTRUCTORS (INSTRUCTORID, FIRSTNAME, LASTNAME, EMAIL, SPECIALITY, HIREDATE, UPDATEDATE)
VALUES (1, 'Angel', 'Hackerman', 'angelhackerman@test.com', 'Frances', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert courses

INSERT INTO courses (COURSENAME, DESCRIPTION, INSTRUCTORID, DURATIONHOURS, LOAD_DATE)
VALUES ('Frances', 'Curso de frances basico', 1, 10, CURRENT_TIMESTAMP)

UPDATE courses
SET courseid = 1
WHERE courseid = 2;

-- Insert student and course

INSERT INTO STUDENT_COURSES (STUDENTID, COURSEID)
VALUES (1,1);

SELECT * FROM STUDENTS;
SELECT * FROM INSTRUCTORS;
SELECT * FROM COURSES;
SELECT * FROM STUDENT_COURSES;